### PR TITLE
Merge custom branch for PREFER_TOP_DOWN into mainline

### PR DESCRIPTION
**Pull request by cbvms123**
This feature was not yet merged into master. If integrated into master we can upgrade our project to latest code line.

### CODE REVIEW

**Comment by miho** [comment]
Feature #27 is now available in the master branch. Please check if it works for you.

**Comment by miho** [comment]
@cbvms123 does the master branch work for you now? Feature #27 has been added.

**Comment by cbvms123** [comment]
Yes, Feature #27 (Prefer top down layout) now works with the master branch.

**Comment by miho** [comment]
Glad to hear that. Then I will close this request for now since master should be functionally equivalent with the passthru branch.

**Pull request closed without merging**
